version: "3"
services:
  backend:
    depends_on:
      - mysqldb
    restart: on-failure
    image: myimage:0.1.0
    ports:
      - 8080:8080
      - 5005:5005
    networks:
      - recipes-net
    environment:
      - URLDB=jdbc:mysql://mysqldb:3306/recipesdb
      - DEFAULTPASSWORD=piwo
      - USERDB=root
      - PASSWDDB=secret

  mysqldb:
    image: mysql:8.0.30
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=recipesdb
    networks:
      - recipes-net
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:

networks:
  recipes-net:


